#!/bin/sh

# Run the test suite before pushing to remote, so the GitLab CI fails less
# often
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# If the log message starts with "WIP:" (work in progress) the push is allowed
# even if the tests fail, since it might be necessary to push to share between
# work environments.

GITLAB_PROJECT_ID=6643206
CI_LINT_OUTPUT=/tmp/gitlab-ci-lint.json

STATUS=0

poetry run pytest -n auto tests/unit || STATUS=1
poetry run pytest -n auto tests/integration || STATUS=1
poetry run mypy duplicate_images tests || STATUS=1
poetry run flake8 duplicate_images tests || STATUS=1
poetry run pylint duplicate_images tests || STATUS=1
poetry run bandit -r duplicate_images -q || STATUS=1

# lint GitLab CI (nod to https://stackoverflow.com/questions/49090675/how-can-i-test-gitlab-ci-yml#68723161 )
if [ "$GITLAB_ACCESS_TOKEN" != "" ]; then
    rm -f "$CI_LINT_OUTPUT"
    jq --null-input --arg yaml "$(cat .gitlab-ci.yml)" '{ content: $yaml }' | \
      curl -s "https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/ci/lint" \
        --header 'Content-Type: application/json' \
        --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" \
        --data @- > "$CI_LINT_OUTPUT"
    echo "GitLab CI valid: $(jq -r .valid < "$CI_LINT_OUTPUT")"
    if [ "$(jq -r .valid <"$CI_LINT_OUTPUT")" != "true" ]; then
        STATUS=1
        echo "errors: $(jq .errors < "$CI_LINT_OUTPUT")"
        echo "warnings: $(jq .warnings < "$CI_LINT_OUTPUT")"
    fi
	#rm -f "$CI_LINT_OUTPUT"
else
    echo "\$GITLAB_ACCESS_TOKEN not set"
fi

# check Changelog is updated
VERSION=$(egrep 'version = ".*"' pyproject.toml | cut -d \" -f 2)
if test -z "$VERSION"; then echo 'version not found in pyproject.toml'; STATUS=1; fi
if ! grep -q "$VERSION" CHANGELOG.md
then echo "$VERSION not found in changelog"; STATUS=1
else echo "$VERSION found in CHANGELOG.md, cool"
fi
if ! fgrep -q "...$VERSION" CHANGELOG.md
then echo "link to $VERSION diff not found in changelog"; STATUS=1
else echo "link to $VERSION diff found in CHANGELOG.md, cool"
fi
if ! fgrep "## [$VERSION] - $(date +%Y-%m-%d)" CHANGELOG.md
then echo "date not set correctly in changelog"; STATUS=1
else echo "date in CHANGELOG.md is $(date +%Y-%m-%d), cool"
fi

if [ $STATUS -gt 0 ]; then
  commitmsg=$(git log --oneline | head -n 1 | cut -d' ' -f 2-)
  if echo "$commitmsg" | grep '^WIP:'; then
    echo >&2 "Found WIP commit, pushing in spite of failed test suite"
    STATUS=0
  fi
fi
echo Status: $STATUS
exit $STATUS
